# SPDX-FileCopyrightText: 2024-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kalzium
confinement: strict
grade: stable
base: core24
adopt-info: kalzium
apps:
  kalzium:
    extensions:
      - kde-neon-6
    common-id: org.kde.kalzium.desktop
    desktop: usr/share/applications/org.kde.kalzium.desktop
    command: usr/bin/kalzium
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kalzium
    bus: session
parts:
  kalzium:
    parse-info:
      - usr/share/metainfo/org.kde.kalzium.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libxml2-dev
      - gettext
      - doxygen
      - graphviz
      - libxml2-utils
      - docbook-xml
      - docbook-xsl
      - libglx-dev
      - libgl-dev
      - libglvnd-dev
      - chemical-mime-data
      - libboost-python-dev
      - libeigen3-dev
      - libfacile-ocaml-dev
      - libglew-dev
      - libsm-dev
      - libpulse0
      - libopenbabel-dev
    stage-packages:
      - chemical-mime-data
      - ocaml-nox
      - libglew-dev
      - libsm6
      - libopenbabel7
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [kalzium]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kalzium
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
