
# SPDX-FileCopyrightText: 2023 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kalzium
confinement: strict
grade: stable
base: core22
adopt-info: kalzium
apps:
    kalzium:
        # extensions:
        # - kde-neon
        common-id: org.kde.kalzium.desktop
        desktop: usr/share/applications/org.kde.kalzium.desktop
        command: usr/bin/kalzium
        plugs:
        - home
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - audio-playback
        - unity7
        - network
        - network-bind
        - cups
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.55.3
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-111-qt-5-15-11-core22:
        content: kf5-5-111-qt-5-15-11-core22-all
        interface: content
        default-provider: kf5-5-111-qt-5-15-11-core22
        target: $SNAP/kf5
    foo-install-cups:
        interface: content
        content: foo
        default-provider: cups
        target: $SNAP_DATA/foo
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kalzium
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-111-qt-5-15-11-core22
        build-snaps:
        - kf5-5-111-qt-5-15-11-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-111-qt-5-15-11-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-111-qt-5-15-11-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kf5-5-111-qt-5-15-11-core22-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
        - &id004
            CRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-111-qt-5-15-11-core22-sdk/current${CRAFT_CMAKE_ARGS:+:$CRAFT_CMAKE_ARGS}
    openbabel:
        after:
        - kde-neon
        plugin: cmake
        build-packages:
        - cmake
        source: https://github.com/openbabel/openbabel/releases/download/openbabel-3-1-1/openbabel-3.1.1-source.tar.bz2
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kf5-5-111-qt-5-15-11-core22-sdk/current"
    kalzium:
        after:
        - kde-neon
        - openbabel
        parse-info:
        - usr/share/metainfo/org.kde.kalzium.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - chemical-mime-data
        - libboost-python-dev
        - libeigen3-dev
        - libfacile-ocaml-dev
        - libglew-dev
        - libkf5khtml-dev
        - libsm-dev
        - libavogadro-dev
        stage-packages:
        - chemical-mime-data
        - ocaml-nox
        - libglew-dev
        - libkf5khtml5
        - libsm6
        - avogadro
        - avogadro-utils
        - kio
        stage-snaps:
        - khelpcenter
        source: .
        source-type: local
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kf5-5-111-qt-5-15-11-core22-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins/"
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-usr/share/lintian"
        build-environment: &id005
        - *id001
        - *id002
        - *id003
        - *id004
    cleanup:
        after:
        - kalzium
        plugin: nil
        override-prime: |
            set -eux
            #unused libs from linters

